url: https://sysopsacademy.github.io
baseurl:

# Site settings
title: SysOps Academy
email: hi@sysops.academy
description: ""


# Team names, titles and social links
people:
- name: Maria Nita
  pic: 1
  position: Site Reliability Engineer
  social:
    - title: twitter
      url: #
    - title: linkedin
      url: #
    - title: github
      url: #

- name: Marius Cotofana
  pic: 2
  position: DevOps
  social:
    - title: twitter
      url: #
    - title: linkedin
      url: #
    - title: github
      url: #

# Social networks
social:
  - title: twitter
    url: http://twitter.com/SysOpsAcademy
  - title: facebook
    url: http://facebook.com
  - title: github
    url: http://github.com/SysOpsAcademy

# Postal address
address:
  - line: Bucharest, Romania

# Build settings
markdown: kramdown
permalink: pretty
